#! /bin/bash
if [ -z "${BASEURL+x}" ]  # Default if not set in config file:
then
        BASEURL=http://rest.randomsanity.org/v1/q
fi

checkbytes() {
        echo "Sanity checking /dev/urandom..." | systemd-cat -p info
        URL="$BASEURL/$1"
        # RESPONSE is an array of response lines from the server
        RESPONSE=( $(wget --quiet --tries=1 --output-document=- --timeout=5 --max-redirect=1 --save-headers "$URL" ) )
        WGET_RESULT=$?
        if [ $WGET_RESULT -ne 0 ]
        then
                echo $WGET_RESULT | systemd-cat -p info
                echo "wget $URL failed: (${WGET_RESULT})" | systemd-cat -p warning
                return $WGET_RESULT
        fi
        
        last=$(( ${#RESPONSE[@]}-1 ))  # Index of last line
        case "${RESPONSE[$last]}" in
            true)
                echo 0 | systemd-cat -p info
                ;;
            false)
                echo 1 | systemd-cat -p warn
                echo "random sanity check failure" | systemd-cat -t randomsanity -p emerg
                ;;
            *)
                echo 1 | systemd-cat -p warning
                echo "Unexpected result from server: ${RESPONSE[$last]}" | systemd-cat -p warning
                return 1
                ;;
        esac

        # RESPONSE contains entropy from the server; mix it in to /dev/urandom:
        cat <<< "${RESPONSE[*]}" >> /dev/urandom

        return 0
}

hexbytes=$(head --bytes=64 /dev/urandom | od -v -t x1 -An | tr -d '\n ')
checkbytes "$hexbytes"
